baseURL = "/"
languageCode = "en"
title = "BlogDevOps"
author = "Renato Ruis"
canonifyurls = true
paginate = 3
publishDir   = "docs"

#googleAnalytics = "Your google analytics tracking ID - optional"
#disqusShortname = "Your shortname for Disqus - optional"

[params]
brand = "BlogDevops"
description = "Minimal blog by Renato Ruis"
#homeimg = "URL to the image used for the home button at the bottom of each post - optional"
bgimg = "https://st2.depositphotos.com/1152339/10274/i/950/depositphotos_102745502-stock-photo-grunge-background-white-brick-wall.jpg"

    
[outputs]
  home = ["HTML", "JSON"]
  page = ["HTML"]

######
# Theme documentation
# https://themes.gohugo.io/aether/
######